version: "3.8"

services:
  postgres_crystal:
    image: postgres
    container_name: postgres_crystal
    environment:
      POSTGRES_USER: ${BASE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BASE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${BASE_POSTGRES_DATABASE}
    volumes:
      - crystal_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgresql
    restart: unless-stopped

  postgres_files:
    image: postgres
    container_name: postgres_files
    environment:
      POSTGRES_USER: ${FILE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${FILE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${FILE_POSTGRES_DATABASE}
    volumes:
      - files_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - postgresql
    restart: unless-stopped

  pgadmin_crystal:
    container_name: pgadmin_crystal
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgresql
    restart: unless-stopped

networks:
  postgresql:
    driver: bridge

volumes:
  crystal_data:
  files_data:
  pgadmin:
